import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // { type: "doc", id: "index", label: "Home" },
    { type: "autogenerated", dirName: "." },
  ],
};

export default sidebars;
